FeelingGoodApp/FeelingGoodApp/Controllers/ExerciseController.cs
using FeelingGoodApp.Data;
using FeelingGoodApp.Data.Models;
using FeelingGoodApp.Models;
using FeelingGoodApp.Services;
using FeelingGoodApp.Services.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FeelingGoodApp.Controllers
{
    public class ExerciseController : Controller
    {
        private readonly IExerciseService _service;
        private readonly FeelingGoodContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;


        public ExerciseController(IExerciseService service, FeelingGoodContext context, UserManager<ApplicationUser> usermanager)
        {
            _service = service;
            _context = context;
            _usermanager = usermanager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _usermanager.GetUserId(User);
            return View(await _context.Exercises.Where(x => x.User.Id == userId).ToListAsync());
        }

        //added details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exercise == null)
            {
                return NotFound();
            }

            return View(exercise);
        }

        //added GET create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult GetExercise()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ShowExercise(UserProfileViewModel model)
        {
            var exercise = new ExerciseViewModel();
            var information = await _service.GetExercise(model);
            var exr = new Exercise();
            var user = await _usermanager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                exr.Pace = information.Met;
                exr.Calories = information.Nf_calories;
                exr.Duration = information.Duration_min;
                exr.User = user;

                exercise.Pace = exr.Pace;
                exercise.Calories = exr.Calories;
                exercise.Duration = exr.Duration;
                exercise.Description = exr.Description;

            }

            if (user != null)// Verifies that a user is logged in and saves the data. Otherwise does not save the data if no user is logged in.
            {
                _context.Exercises.Add(exr);
                await _context.SaveChangesAsync();
                exercise.Id = exr.Id.Value;
            }
            return View(exercise); // need to add the ability to edit the quantity
        }

        //added GET create
        //public IActionResult Create()
        //{
        //    return View();
        //}
        //[HttpPost]
        ////added Post Create and Bind to protect against overposting attacks
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name,User")] ExerciseInfo exercise)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        exercise.User = await _usermanager.GetUserAsync(User);
        //        _context.Add(exercise);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(exercise);
        //}
        // Get Exercise Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var exercise = await _context.Exercises.FindAsync(id);
            var exr = new UserProfileViewModel
            {
                Id = exercise.Id.Value,

            };
            if (exercise == null)
            {
                return NotFound();
            }
            return View(exr);
        }
        // Added POST Exercise Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,User")] UserProfileViewModel exercise)
        {
            if (id != exercise.Id)
            {
                return NotFound();
            }
            // this needs to call the api to get a new Exercise based off of the new information...

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exercise);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExerciseExists(exercise.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(exercise);
        }
        //Added Get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises.FindAsync(id);
            var exr = new UserProfileViewModel
            {
                Id = exercise.Id.Value
            };

            var model = new ExerciseViewModel
            {
                Id = exercise.Id.Value
            };
            //var toDo = await _context.Exercises
            //    .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        //Added Post Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Exercises = await _context.Exercises.FindAsync(id);
            _context.Exercises.Remove(Exercises);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ExerciseExists(int id)
        {
            return _context.Exercises.Any(e => e.Id == id);
        }
        // Get Exercise Edit
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var exercise = await _context.Exercises.FindAsync(id);
        //    if (exercise == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(exercise);
        //}
        // Added POST Exercise Edit
       
        //Added Get Delete
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var toDo = await _context.Exercises
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (toDo == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(toDo);
        //}
        ////Added Post Delete
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]

        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var Exercises = await _context.Exercises.FindAsync(id);
        //    _context.Exercises.Remove(Exercises);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}



        private bool exerciseExists(int id)
        {
            return _context.Exercises.Any(e => e.Id == id);
        }
    }
}

FeelingGoodApp/FeelingGoodApp/Controllers/NutritionController.cs
using FeelingGoodApp.Data;
using FeelingGoodApp.Data.Models;
using FeelingGoodApp.Models;
using FeelingGoodApp.Services;
using FeelingGoodApp.Services.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace FeelingGoodApp.Controllers
{
    public class NutritionController : Controller
    {
        private readonly INutritionService _service;
        private readonly UserManager<ApplicationUser> _usermanager;
        private readonly FeelingGoodContext _context;
        // GET: NutritionController

        public NutritionController(INutritionService service, UserManager<ApplicationUser> usermanager, FeelingGoodContext context)
        {
            _service = service;
            _usermanager = usermanager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _usermanager.GetUserId(User);
            return View(await _context.MealData.Where
                (x => x.User.Id == userId).ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> GetNutrition(NutritionViewModel model)
        {
            var information = await _service.GetFieldsAsync(model.item_name);
            Nutrition FoodChoice = new Nutrition();
            var nutritionModel = new NutritionViewModel();
            var user = await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                FoodChoice.Item_name = information.hits.FirstOrDefault().fields.item_name;
                FoodChoice.Nf_calories = information.hits.FirstOrDefault().fields.nf_calories;
                FoodChoice.Quantity = information.hits.FirstOrDefault().fields.nf_serving_size_qty;
                FoodChoice.User = user;

                nutritionModel.item_name = FoodChoice.Item_name;
                nutritionModel.nf_calories = FoodChoice.Nf_calories;
                nutritionModel.Quantity = FoodChoice.Quantity;

            }
            _context.MealData.Add(FoodChoice);
            await _context.SaveChangesAsync();
            nutritionModel.Id = FoodChoice.Id;
            return View(nutritionModel); // need to add the ability to edit the quantity
        }
        public IActionResult AddFood()
        {

            return View();
        }
        // GET: NutritionController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var meal = await _context.MealData.FirstOrDefaultAsync(m => m.Id == id);
            if (meal == null)
            {
                return NotFound();
            }
            return View(meal);

        //// GET: NutritionController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: NutritionController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(GetNutrition));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}


        // GET: NutritionController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var nutrition = await _context.MealData.FindAsync(id);

            if (nutrition is null)
            {
                return NotFound();
            }

            var nut = new NutritionViewModel
            {
                Id = nutrition.Id,

            };
            if (nutrition == null)
            {
                return NotFound();
            }
            return View(nut);
        }

        // POST: NutritionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NutritionViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: NutritionController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.MealData.FindAsync(id);
            var model = new NutritionViewModel
            {
                Id = food.Id
            };

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: NutritionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.MealData.FindAsync(id);
            _context.MealData.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.MealData.Any(e => e.Id == id);
        }
    }
}

FeelingGoodApp/FeelingGoodApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FeelingGoodApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FeelingGoodApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="SearchPlaces">Place Near You</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="GetExercise">Log Exercise</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nutrition" asp-action="AddFood">Get Nutrition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>

                        <li class="nav-item">
            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowExercise">Show Exercise</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetLongLat">Find A Place Near You</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Search">Search Food</a>
        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center text-black-50" style="color: black; font-weight: bolder">
            &hearts; &reg; &copy; 2021 - Feeling Good App - The Right Brothers &trade; &reg; &hearts;
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>